language: go

go:
  - 1.11.x
  - master

before_script:
  # Go get our deps.
  - go get -v ./...

script:
  - go build main.go

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
